[package]
name = "d3_channels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "pool"
path = "src/pool.rs"

[[bin]]
name = "rayon_pool"
path = "src/rayon_pool.rs"

[dependencies]
rayon = "1.5.1"
